const TOOL_NAMES = {
  DICOM_SEG_TEMP_CROSSHAIRS_TOOL: 'DICOMSegTempCrosshairsTool',
  DICOM_SEG_CUSTOM_TOOL: 'DICOMSegCustomTool',
  DICOM_SEG_CUSTOM_TOOL_3D: 'DICOMSegCustomTool3D',
  SYNC_BRUSH_TOOL: 'SyncBrush',
};

export default TOOL_NAMES;
